name: Order Reminder for Clients

on:
  # 1. Запуск за розкладом (Cron)
  schedule:
    # 15:00 UTC = 17:00 за Києвом (взимку)
    - cron: '0 15 * * *'
    # 19:00 UTC = 21:00 за Києвом
    - cron: '0 19 * * *'

  # 2. Дозволяє запускати скрипт ВРУЧНУ (з вкладки Actions)
  workflow_dispatch:

  # 3. Запускати при кожному оновленні коду (для тестів)
  push:
    branches:
      - main

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run reminder script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
        run: python scheduler.py
